### ISSUE TITLE
What is "add"?

### ISSUE THREAD

**Issue by ipepsiii** [kukuclass/kuku-junior#11]
Todolist.prototype = {
        add({title, content}) {
            todolist.push(new Todo({title, content}));
        },
}
这个原型对象中的 
 add({title, content}) {
            todolist.push(new Todo({title, content}));
        },
是函数还是其他东西？

**Comment by snowjujube** [comment]
这里就是指Todolist的原型上拥有这个方法呀，上边的写法等同于 `{ add: function() {} }`

**Comment by ipepsiii** [comment]
> 这里就是指Todolist的原型上拥有这个方法呀，上边的写法等同于 `{ add: function() {} }`

了解
