### ISSUE TITLE
controller中的addTodo部分为什么要加入清除旧的model状态和加入新的model状态

### ISSUE THREAD

**Issue by ipepsiii** [kukuclass/kuku-junior#13]
addTodo: function () {
     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       if (todolistView.input.title.value && todolistView.input.content.value) {
           &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        todolistModel.add({
                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  &nbsp;&nbsp;&nbsp;&nbsp; title: todolistView.input.title.value,
                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  &nbsp;&nbsp;&nbsp;&nbsp; content: todolistView.input.content.value
                   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; });
                    // 清除旧的model状态
                    TodolistController.prototype.clearAllTodosFromView();
                    // 设置新的model状态
                    TodolistController.prototype.addAllTodosIntoView();
                }
            },

**Comment by snowjujube** [comment]
试想，你更新了`model`，但`view`并没有同步，需要你手动同步的，这个时候有两种做法
1. 把你新增的数据变成`view`需要的样式，增加给之前的`view`
2. 之前的`view`对应的是你更新前的`model`，那么应该将它清除，再去创建一份新的`model` -> `view`的映射，重新渲染新的`model`

**Comment by ipepsiii** [comment]
> 试想，你更新了`model`，但`view`并没有同步，需要你手动同步的，这个时候有两种做法
> 
> 1. 把你新增的数据变成`view`需要的样式，增加给之前的`view`
> 2. 之前的`view`对应的是你更新前的`model`，那么应该将它清除，再去创建一份新的`model` -> `view`的映射，重新渲染新的`model`

懂了
