### ISSUE TITLE
关于函数参数解构

### ISSUE THREAD

**Issue by LASIWan** [kukuclass/kuku-junior#14]
```
function move({x = 0, y = 0} = {}) {
  return [x, y];
}

move({x: 3, y: 8}); // [3, 8]
move({x: 3}); // [3, 0]
move({}); // [0, 0]
move(); // [0, 0]
```

```
function move({x, y} = { x: 0, y: 0 }) {
  return [x, y];
}

move({x: 3, y: 8}); // [3, 8]
move({x: 3}); // [3, undefined]
move({}); // [undefined, undefined]
move(); // [0, 0]
````
这两段代码的区别有点不太明白 @snowjujube

**Comment by snowjujube** [comment]
这里蛮好理解的吧，第二段代码如果传了参数就会按照传入参数的值来解构结果

所以自然会得到y = undefined

第一段代码将解构的结果做了默认值的赋值，这个时候如果解构不到y的值，会按照默认值处理

**Comment by LASIWan** [comment]
就是一二段代码的第三个move有点不太懂，为啥一个是[0,0]，一个是[undefined, undefined]

**Comment by LASIWan** [comment]
> 
> 
> 这里蛮好理解的吧，第二段代码如果传了参数就会按照传入参数的值来解构结果
> 
> 所以自然会得到y = undefined
> 
> 第一段代码将解构的结果做了默认值的赋值，这个时候如果解构不到y的值，会按照默认值处理

就是一二段代码的第三个move有点不太懂，为啥一个是[0,0]，一个是[undefined, undefined]

**Comment by snowjujube** [comment]
第一个方法 {x = 0, y = 0} = {} 这里，假如传入{}做解构, {}会解构得到x和y都是undefined，所以会都赋值默认值0
第二个方法{x, y} = {x: 0,y: 0}，你传递了{}作为参数，因此不会做解构; {}就已经是参数了，也就是说只有move(undefined)的时候，才会赋值参数为{ x: 0, y: 0 }, {}又不是undefined, 自然覆盖了默认值
