### ISSUE TITLE
Ubuntu安装创建新用户

### ISSUE THREAD

**Issue by LASIWan** [kukuclass/kuku-junior#3]
Enter username: 
New password:
这里创建好用户名之后，输入password时，命令行不显示你的输入，实际你已经输入了，但并不显示
因此在New password后直接一次性输入你的密码后enter
接着再次retype，两次密码一致则创建成功，最终显示successfully

**Comment by snowjujube** [comment]
nice 大家也要避开这个坑 密码其实是不显示的  linux unix都这样~

**Comment by snowjujube** [comment]
@mondhaus @ChronicCH @Yao0420 @ipepsiii
