### ISSUE TITLE
void强制类型转换

### ISSUE THREAD

**Issue by LASIWan** [kukuclass/kuku-junior#4]
void运算符的作用是执行一个表达式，然后不返回任何值，或者说返回undefined。
实例：
var x=3；
void（x=5） \\undefined
x                    \\5

void 运算符能对给定的表达式进行求值，然后返回 undefined，因此后面第二行的返回值为undefined，而x的值变为5

**Comment by snowjujube** [comment]
@mondhaus @ChronicCH @ipepsiii @Yao0420 大家看看这道题
