### ISSUE TITLE
关于<>必选项 和[]可选项的问题

### ISSUE THREAD

**Issue by ipepsiii** [kukuclass/kuku-junior#5]
<>   尖括号内本来是必选项， [ ] 方括号内是可选项   
但是zsh文档里出现了   zsh [<options>] [<argument> ...]     这是为什么？

**Comment by LASIWan** [comment]
我的理解应该和必选项和可选项没啥关系
在Ubuntu里type zsh --help会出来帮助文档
Usage: zsh [<options>] [<argument> ...]
因此这里应该是一个示例，代表用法：zsh [<选项>] [<参数> ...]
后面给你列举了可用的option，从--aliases一直到--zle，应该不用纠结于这两种括号

**Comment by LASIWan** [comment]
另外，可以挂vpn用谷歌搜索，或者可以在stackflow上搜一下相关的知识，比百度好使。

**Comment by LASIWan** [comment]
顺带说一下[[ ]]和(( ))
[[ ]]用来用于比较字符串、判断文件等，如
if [[ "$str" == "name" || "$str" == "value" ]]{
    echo "$str"
}
(( ))用来比较数值，，里边可以调用各种数值相关的函数，如
if ((num > 3 && num + 3 < 10)){
    echo $num
}

**Comment by snowjujube** [comment]
> 顺带说一下[[ ]]和(( ))
> [[ ]]用来用于比较字符串、判断文件等，如
> if [[ "$str" == "name" || "$str" == "value" ]]{
> echo "$str"
> }
> (( ))用来比较数值，，里边可以调用各种数值相关的函数，如
> if ((num > 3 && num + 3 < 10)){
> echo $num
> }

这里是shell嘛？？？

**Comment by LASIWan** [comment]
> 
> 
> > 顺带说一下[[ ]]和(( ))
> > [[ ]]用来用于比较字符串、判断文件等，如
> > if [[ "$str" == "name" || "$str" == "value" ]]{
> > echo "$str"
> > }
> > (( ))用来比较数值，，里边可以调用各种数值相关的函数，如
> > if ((num > 3 && num + 3 < 10)){
> > echo $num
> > }
> 
> 这里是shell嘛？？？

是啊，昨天看zsh教程看到得
