### ISSUE TITLE
如何配置webstorm和hyper

### ISSUE THREAD

**Issue by LASIWan** [kukuclass/kuku-junior#6]
@Yao0420 @ChronicCH @ipepsiii

**Comment by ipepsiii** [comment]
把webstorm的terminal的路径改为‘C:\\Windows\\System32\\cmd.exe’

**Comment by snowjujube** [comment]
> 把webstorm的terminal的路径改为‘C:\Windows\System32\cmd.exe’

还需要启动的环境变量哦 @ChronicCH @Yao0420 可以copy分享一下
