### ISSUE TITLE
使用闭包写todolist

### ISSUE THREAD

**Issue by LASIWan** [kukuclass/kuku-junior#7]
增删改查里面的删，是否应该是对原数组进行改变，
如果用filter返回一个新数组，但再打印原始数组是不是会没有改变？
      function removeTodo(index) {
           return list = list.filter(todo => todo.id !== index)
     }

**Comment by ipepsiii** [comment]
对的，filter(）函数只会返回符合括号里条件的部分元素，但是原数组并没有改变，这个题里面只是用返回的部分元素覆盖率原数组，从而间接地实现"删"

**Comment by LASIWan** [comment]
> 
> 
> 对的，filter(）函数只会返回符合括号里条件的部分元素，但是原数组并没有改变，这个题里面只是用返回的部分元素覆盖率原数组，从而间接地实现"删"

是，但是删的话应该是直接从原数组里面删掉，因为就不需要此项list了，调这个函数可以返回一个删掉此项的新数组，但还是没有将此项从我的todolist中删掉啊。不知道我的理解对不对

**Comment by LASIWan** [comment]
我脑残了，又没反应过来一个东西，运行了一下才知道哪块想错了
